//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaiavka
    {
        public decimal ID { get; set; }
        public System.DateTime Data { get; set; }
        public string Oborudovanie { get; set; }
        public Nullable<decimal> NeispravnostID { get; set; }
        public string Opisanie { get; set; }
        public decimal KlientID { get; set; }
        public decimal StatusID { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Neispravnost Neispravnost { get; set; }
        public virtual Status Status { get; set; }
    }
}
